// Mock data for development - will be replaced with real DB queries

export const mockProducer = {
  id: 'producer-1',
  name: 'Studio Flow',
  email: 'producer@studioflow.app',
  role: 'PRODUCER' as const,
  locale: 'he',
};

export const mockClients = [
  {
    id: 'client-1',
    name: 'דניאל לוי',
    email: 'daniel@email.com',
    phone: '054-1234567',
    totalPaid: 8000,
    totalOwed: 4000,
    projectCount: 2,
    activeProjects: 1,
    lastSession: '2026-02-08',
    source: 'המלצה',
  },
  {
    id: 'client-2',
    name: 'מיכל כהן',
    email: 'michal@email.com',
    phone: '052-9876543',
    totalPaid: 12000,
    totalOwed: 0,
    projectCount: 3,
    activeProjects: 1,
    lastSession: '2026-02-05',
    source: 'אינסטגרם',
  },
  {
    id: 'client-3',
    name: 'יוסי אברהם',
    email: 'yossi@email.com',
    phone: '050-5555555',
    totalPaid: 3500,
    totalOwed: 3500,
    projectCount: 1,
    activeProjects: 1,
    lastSession: '2026-02-10',
    source: 'מכללה',
  },
  {
    id: 'client-4',
    name: 'נועה ישראלי',
    email: 'noa@email.com',
    phone: '053-1112222',
    totalPaid: 5000,
    totalOwed: 2000,
    projectCount: 1,
    activeProjects: 1,
    lastSession: '2026-01-28',
    source: 'אתר',
  },
  {
    id: 'client-5',
    name: 'אדם שלום',
    email: 'adam@email.com',
    phone: '058-3334444',
    totalPaid: 15000,
    totalOwed: 0,
    projectCount: 4,
    activeProjects: 0,
    lastSession: '2026-01-15',
    source: 'המלצה',
  },
  {
    id: 'client-6',
    name: 'רותם דהן',
    email: 'rotem@email.com',
    phone: '054-7778888',
    totalPaid: 0,
    totalOwed: 7000,
    projectCount: 1,
    activeProjects: 1,
    lastSession: null,
    source: 'טיקטוק',
  },
];

export type SongStage = 'SKETCH' | 'PRODUCTION' | 'RECORDING' | 'EDITING' | 'MIXING' | 'MIX_REVISIONS' | 'MASTERING' | 'DELIVERED';

export const songStages: SongStage[] = [
  'SKETCH',
  'PRODUCTION',
  'RECORDING',
  'EDITING',
  'MIXING',
  'MIX_REVISIONS',
  'MASTERING',
  'DELIVERED',
];

export const stageLabels: Record<string, { he: string; en: string }> = {
  SKETCH: { he: 'סקיצה', en: 'Sketch' },
  PRODUCTION: { he: 'הפקה', en: 'Production' },
  RECORDING: { he: 'הקלטה', en: 'Recording' },
  EDITING: { he: 'עריכה', en: 'Editing' },
  MIXING: { he: 'מיקס', en: 'Mixing' },
  MIX_REVISIONS: { he: 'תיקוני מיקס', en: 'Mix Revisions' },
  MASTERING: { he: 'מאסטרינג', en: 'Mastering' },
  DELIVERED: { he: 'נמסר', en: 'Delivered' },
};

export const mockSongs = [
  {
    id: 'song-1',
    projectId: 'project-1',
    clientId: 'client-1',
    clientName: 'דניאל לוי',
    title: 'לילה בתל אביב',
    stage: 'MIXING' as SongStage,
    genre: 'Pop',
    bpm: 120,
    key: 'Am',
    sessionCount: 6,
    lastUpdated: '2026-02-08',
  },
  {
    id: 'song-2',
    projectId: 'project-1',
    clientId: 'client-1',
    clientName: 'דניאל לוי',
    title: 'בוקר חדש',
    stage: 'PRODUCTION' as SongStage,
    genre: 'Pop/Rock',
    bpm: 130,
    key: 'C',
    sessionCount: 3,
    lastUpdated: '2026-02-06',
  },
  {
    id: 'song-3',
    projectId: 'project-2',
    clientId: 'client-2',
    clientName: 'מיכל כהן',
    title: 'רוח חופשית',
    stage: 'RECORDING' as SongStage,
    genre: 'Acoustic',
    bpm: 90,
    key: 'G',
    sessionCount: 4,
    lastUpdated: '2026-02-05',
  },
  {
    id: 'song-4',
    projectId: 'project-3',
    clientId: 'client-3',
    clientName: 'יוסי אברהם',
    title: 'הדרך הביתה',
    stage: 'SKETCH' as SongStage,
    genre: 'Hip-Hop',
    bpm: 95,
    key: 'Dm',
    sessionCount: 2,
    lastUpdated: '2026-02-10',
  },
  {
    id: 'song-5',
    projectId: 'project-4',
    clientId: 'client-4',
    clientName: 'נועה ישראלי',
    title: 'כוכבים',
    stage: 'MIX_REVISIONS' as SongStage,
    genre: 'R&B',
    bpm: 85,
    key: 'Eb',
    sessionCount: 7,
    lastUpdated: '2026-01-28',
  },
  {
    id: 'song-6',
    projectId: 'project-5',
    clientId: 'client-6',
    clientName: 'רותם דהן',
    title: 'אש וזהב',
    stage: 'SKETCH' as SongStage,
    genre: 'Electronic',
    bpm: 128,
    key: 'F#m',
    sessionCount: 0,
    lastUpdated: '2026-02-11',
  },
  {
    id: 'song-7',
    projectId: 'project-2',
    clientId: 'client-2',
    clientName: 'מיכל כהן',
    title: 'עוד יום',
    stage: 'MASTERING' as SongStage,
    genre: 'Acoustic',
    bpm: 100,
    key: 'D',
    sessionCount: 8,
    lastUpdated: '2026-02-03',
  },
  {
    id: 'song-8',
    projectId: 'project-6',
    clientId: 'client-5',
    clientName: 'אדם שלום',
    title: 'מנגינות',
    stage: 'DELIVERED' as SongStage,
    genre: 'Pop',
    bpm: 110,
    key: 'Bb',
    sessionCount: 9,
    lastUpdated: '2026-01-15',
  },
];

export const mockSessions = [
  {
    id: 'session-1',
    songId: 'song-1',
    songTitle: 'לילה בתל אביב',
    clientName: 'דניאל לוי',
    type: 'MIXING',
    status: 'CONFIRMED',
    title: 'מיקס - לילה בתל אביב',
    startTime: '2026-02-12T14:00:00',
    endTime: '2026-02-12T17:00:00',
    duration: 180,
    isProducerOnly: false,
  },
  {
    id: 'session-2',
    songId: 'song-4',
    songTitle: 'הדרך הביתה',
    clientName: 'יוסי אברהם',
    type: 'SKETCH',
    status: 'CONFIRMED',
    title: 'סקיצה - הדרך הביתה',
    startTime: '2026-02-13T10:00:00',
    endTime: '2026-02-13T13:00:00',
    duration: 180,
    isProducerOnly: false,
  },
  {
    id: 'session-3',
    songId: 'song-3',
    songTitle: 'רוח חופשית',
    clientName: 'מיכל כהן',
    type: 'RECORDING',
    status: 'PENDING',
    title: 'הקלטה - רוח חופשית',
    startTime: '2026-02-14T16:00:00',
    endTime: '2026-02-14T19:00:00',
    duration: 180,
    isProducerOnly: false,
  },
  {
    id: 'session-4',
    songId: 'song-1',
    songTitle: 'לילה בתל אביב',
    clientName: '',
    type: 'EDITING',
    status: 'CONFIRMED',
    title: 'עריכת קולות - לילה בתל אביב',
    startTime: '2026-02-12T10:00:00',
    endTime: '2026-02-12T13:00:00',
    duration: 180,
    isProducerOnly: true,
  },
  {
    id: 'session-5',
    songId: 'song-2',
    songTitle: 'בוקר חדש',
    clientName: 'דניאל לוי',
    type: 'PRODUCTION',
    status: 'CONFIRMED',
    title: 'הפקה - בוקר חדש',
    startTime: '2026-02-15T11:00:00',
    endTime: '2026-02-15T14:00:00',
    duration: 180,
    isProducerOnly: false,
  },
];

export const mockPayments = [
  {
    id: 'pay-1',
    clientId: 'client-1',
    clientName: 'דניאל לוי',
    projectName: 'סינגל - לילה בתל אביב',
    amount: 4000,
    type: 'ADVANCE',
    status: 'PAID',
    dueDate: '2026-01-15',
    paidAt: '2026-01-15',
    installmentNum: 1,
    totalInstallments: 2,
  },
  {
    id: 'pay-2',
    clientId: 'client-1',
    clientName: 'דניאל לוי',
    projectName: 'סינגל - לילה בתל אביב',
    amount: 4000,
    type: 'FINAL',
    status: 'PENDING',
    dueDate: '2026-02-15',
    paidAt: null,
    installmentNum: 2,
    totalInstallments: 2,
  },
  {
    id: 'pay-3',
    clientId: 'client-3',
    clientName: 'יוסי אברהם',
    projectName: 'סינגל - הדרך הביתה',
    amount: 3500,
    type: 'ADVANCE',
    status: 'PAID',
    dueDate: '2026-02-01',
    paidAt: '2026-02-01',
    installmentNum: 1,
    totalInstallments: 2,
  },
  {
    id: 'pay-4',
    clientId: 'client-4',
    clientName: 'נועה ישראלי',
    projectName: 'סינגל - כוכבים',
    amount: 2000,
    type: 'FINAL',
    status: 'OVERDUE',
    dueDate: '2026-02-01',
    paidAt: null,
    installmentNum: 3,
    totalInstallments: 3,
  },
  {
    id: 'pay-5',
    clientId: 'client-6',
    clientName: 'רותם דהן',
    projectName: 'סינגל - אש וזהב',
    amount: 3500,
    type: 'ADVANCE',
    status: 'PENDING',
    dueDate: '2026-02-11',
    paidAt: null,
    installmentNum: 1,
    totalInstallments: 2,
  },
];

export const mockStats = {
  totalRevenue: 43500,
  monthlyRevenue: 11500,
  pendingPayments: 16500,
  overduePayments: 2000,
  activeClients: 5,
  totalClients: 6,
  activeSongs: 7,
  completedSongs: 1,
  sessionsThisWeek: 4,
  sessionsThisMonth: 12,
  avgSessionsPerSong: 5.5,
  avgRevenuePerSong: 5437,
};
